package com.ademe.mapretro.utils.divers

import com.ademe.mapretro.R
import com.ademe.mapretro.utils.marker.Marker
import com.ademe.mapretro.utils.marker.MarkerType

val markerZaap = listOf(
    Marker(
        R.string.zaap,
        R.string.bonta,
        -32,
        -58,
        MarkerType.ZAAP
    ),
    Marker(
        R.string.zaap,
        R.string.cania_rocheuse,
        -14,
        -47,
        MarkerType.ZAAP
    ),
    Marker(
        R.string.zaap,
        R.string.brigandins,
        -18,
        -26,
        MarkerType.ZAAP
    ),
    Marker(
        R.string.zaap,
        R.string.cania_massif,
        -20,
        -20,
        MarkerType.ZAAP
    ),
    Marker(
        R.string.zaap,
        R.string.tainela,
        1,
        -32,
        MarkerType.ZAAP
    ),
    Marker(
        R.string.zaap,
        R.string.pandala_feu,
        29,
        -49,
        MarkerType.ZAAP
    ),
    Marker(
        R.string.zaap,
        R.string.pandala_terre,
        30,
        -38,
        MarkerType.ZAAP
    ),
    Marker(
        R.string.zaap,
        R.string.pandala_neutre,
        26,
        -37,
        MarkerType.ZAAP
    ),
    Marker(
        R.string.zaap,
        R.string.pandala_air,
        17,
        -31,
        MarkerType.ZAAP
    ),
    Marker(
        R.string.zaap,
        R.string.pandala_eau,
        23,
        -22,
        MarkerType.ZAAP
    ),
    Marker(
        R.string.zaap,
        R.string.astrub_cite,
        4,
        -19,
        MarkerType.ZAAP
    ),
    Marker(
        R.string.zaap,
        R.string.amakna_montagne,
        -5,
        -8,
        MarkerType.ZAAP
    ),
    Marker(
        R.string.zaap,
        R.string.amakna_chateau,
        -3,
        -5,
        MarkerType.ZAAP
    ),
    Marker(
        R.string.zaap,
        R.string.amakna_madrestam,
        7,
        -4,
        MarkerType.ZAAP
    ),
    Marker(
        R.string.zaap,
        R.string.amakna_village,
        7,
        -4,
        MarkerType.ZAAP
    ),
    Marker(
        R.string.zaap,
        R.string.amakna_milli,
        5,
        7,
        MarkerType.ZAAP
    ),
    Marker(
        R.string.zaap,
        R.string.amakna_bord_foret,
        -1,
        13,
        MarkerType.ZAAP
    ),
    Marker(
        R.string.zaap,
        R.string.amakna_porte_sufokia,
        10,
        22,
        MarkerType.ZAAP
    ),
    Marker(
        R.string.zaap,
        R.string.amakna_chateau,
        3,
        -5,
        MarkerType.ZAAP
    ),
    Marker(
        R.string.zaap,
        R.string.amakna_scara,
        -1,
        24,
        MarkerType.ZAAP
    ),
    Marker(
        R.string.zaap,
        R.string.moon_plage,
        35,
        12,
        MarkerType.ZAAP
    ),
    Marker(
        R.string.zaap,
        R.string.wabbits_ile,
        25,
        -4,
        MarkerType.ZAAP
    ),
    Marker(
        R.string.zaap,
        R.string.dopeuls,
        -34,
        -8,
        MarkerType.ZAAP
    ),
    Marker(
        R.string.zaap,
        R.string.koalak_village,
        -16,
        1,
        MarkerType.ZAAP
    ),
    Marker(
        R.string.zaap,
        R.string.sidimote,
        -24,
        12,
        MarkerType.ZAAP
    ),
    Marker(
        R.string.zaap,
        R.string.brakmar,
        -25,
        40,
        MarkerType.ZAAP
    ),
    Marker(
        R.string.zaap,
        R.string.oto_village,
        -46,
        18,
        MarkerType.ZAAP
    )
)