package com.ademe.mapretro.utils.divers

import com.ademe.mapretro.R
import com.ademe.mapretro.utils.marker.Marker
import com.ademe.mapretro.utils.marker.MarkerType

val markerMine = listOf(
    Marker(
        R.string.mine_astrub,
        R.string.empty,
        9,
        -23,
        MarkerType.MINES
    ),
    Marker(
        R.string.mine_village_amakna,
        R.string.empty,
        0,
        -3,
        MarkerType.MINES
    ),
    Marker(
        R.string.mine_craque,
        R.string.empty,
        -2,
        4,
        MarkerType.MINES
    ),
    Marker(
        R.string.mine_montage_craque,
        R.string.empty,
        -3,
        -4,
        MarkerType.MINES
    ),
    Marker(
        R.string.mine_sadi,
        R.string.empty,
        -3,
        9,
        MarkerType.MINES
    ),
    Marker(
        R.string.mine_foret_amakna,
        R.string.empty,
        5,
        19,
        MarkerType.MINES
    ),
    Marker(
        R.string.mine_bellus,
        R.string.empty,
        10,
        11,
        MarkerType.MINES
    ),
    Marker(
        R.string.mine_mulou,
        R.string.empty,
        4,
        28,
        MarkerType.MINES
    ),
    Marker(
        R.string.mine_porcos,
        R.string.empty,
        1,
        32,
        MarkerType.MINES
    ),
    Marker(
        R.string.mine_porcos,
        R.string.empty,
        -1,
        33,
        MarkerType.MINES
    ),
    Marker(
        R.string.mine_sidi,
        R.string.empty,
        -25,
        24,
        MarkerType.MINES
    ),
    Marker(
        R.string.mine_brak,
        R.string.empty,
        -22,
        32,
        MarkerType.MINES
    ),
    Marker(
        R.string.mine_bord_brak,
        R.string.empty,
        -25,
        46,
        MarkerType.MINES
    )
)
