package com.ademe.mapretro.utils.divers

import com.ademe.mapretro.R
import com.ademe.mapretro.utils.marker.Marker
import com.ademe.mapretro.utils.marker.MarkerType

val markerPhenix = listOf(
    Marker(
        R.string.phenix,
        R.string.brakmar,
        -26,
        35,
        MarkerType.PHENIX
    ),
    Marker(
        R.string.phenix,
        R.string.brakmar,
        -23,
        38,
        MarkerType.PHENIX
    ),
    Marker(
        R.string.phenix,
        R.string.sidimote,
        -14,
        31,
        MarkerType.PHENIX
    ),
    Marker(
        R.string.phenix,
        R.string.koalak_cimetiere,
        -10,
        13,
        MarkerType.PHENIX
    ),
    Marker(
        R.string.phenix,
        R.string.astrub_tofus,
        2,
        -12,
        MarkerType.PHENIX
    ),
    Marker(
        R.string.phenix,
        R.string.astrub_bouftou,
        5,
        -9,
        MarkerType.PHENIX
    ),
    Marker(
        R.string.phenix,
        R.string.amakna_madrestam,
        12,
        -7,
        MarkerType.PHENIX
    ),
    Marker(
        R.string.phenix,
        R.string.amakna_bandit,
        12,
        12,
        MarkerType.PHENIX
    ),
    Marker(
        R.string.phenix,
        R.string.amakna_foret,
        10,
        19,
        MarkerType.PHENIX
    ),
    Marker(
        R.string.phenix,
        R.string.amakna_porcos,
        -1,
        33,
        MarkerType.PHENIX
    ),
    Marker(
        R.string.phenix,
        R.string.bonta,
        -33,
        -57,
        MarkerType.PHENIX
    ),
    Marker(
        R.string.phenix,
        R.string.bonta,
        -30,
        -54,
        MarkerType.PHENIX
    ),
    Marker(
        R.string.phenix,
        R.string.ile_minotoror,
        -41,
        -17,
        MarkerType.PHENIX
    ),
    Marker(
        R.string.phenix,
        R.string.oto_plage,
        -58,
        18,
        MarkerType.PHENIX
    ),
    Marker(
        R.string.phenix,
        R.string.oto_naufrage,
        -43,
        0,
        MarkerType.PHENIX
    ),
    Marker(
        R.string.phenix,
        R.string.cania,
        -11,
        -54,
        MarkerType.PHENIX
    ),
    Marker(
        R.string.phenix,
        R.string.pandala,
        24,
        -43,
        MarkerType.PHENIX
    ),
    Marker(
        R.string.phenix,
        R.string.pandala_neutre_foret,
        27,
        -33,
        MarkerType.PHENIX
    ),
    Marker(
        R.string.phenix,
        R.string.wabbits_ile,
        25,
        -4,
        MarkerType.PHENIX
    ),
    Marker(
        R.string.phenix,
        R.string.moon_plage,
        36,
        5,
        MarkerType.PHENIX
    )
)
