package com.ademe.mapretro.utils.places

import com.ademe.mapretro.R
import com.ademe.mapretro.utils.marker.MarkerLieu
import com.ademe.mapretro.utils.marker.MarkerType

val markerAtelierBouclier = listOf(
    MarkerLieu(
        R.string.atelier_bou,
        R.string.pandala_air,
        17,
        -34,
        MarkerType.ATELIER_BOUBOU
    ),
    MarkerLieu(
        R.string.atelier_bou,
        R.string.pandala_terre,
        30,
        -37,
        MarkerType.ATELIER_BOUBOU
    ),
    MarkerLieu(
        R.string.atelier_bou,
        R.string.pandala_eau,
        22,
        -23,
        MarkerType.ATELIER_BOUBOU
    )
)

val markerAtelierBucheron = listOf(
    MarkerLieu(
        R.string.atelier_buch,
        R.string.pandala_neutre,
        26,
        -36,
        MarkerType.ATELIER_BUCHERON
    ),
    MarkerLieu(
        R.string.atelier_buch,
        R.string.astrub_foret,
        1,
        -25,
        MarkerType.ATELIER_BUCHERON
    ),
    MarkerLieu(
        R.string.atelier_buch,
        R.string.amakna_foret,
        6,
        16,
        MarkerType.ATELIER_BUCHERON
    ),
    MarkerLieu(
        R.string.atelier_buch,
        R.string.amakna_milli,
        4,
        8,
        MarkerType.ATELIER_BUCHERON
    ),
    MarkerLieu(
        R.string.atelier_buch,
        R.string.amakna_scara,
        4,
        30,
        MarkerType.ATELIER_BUCHERON
    ),
    MarkerLieu(
        R.string.atelier_buch,
        R.string.bonta,
        -23,
        -56,
        MarkerType.ATELIER_BUCHERON
    )
)

val markerAtelierPaysan = listOf(
    MarkerLieu(
        R.string.atelier_paysan,
        R.string.astrub_champ,
        7,
        -25,
        MarkerType.ATELIER_PAYSAN
    ),
    MarkerLieu(
        R.string.atelier_paysan,
        R.string.amakna_champ,
        5,
        6,
        MarkerType.ATELIER_PAYSAN
    ),
    MarkerLieu(
        R.string.atelier_paysan,
        R.string.amakna_scara,
        2,
        25,
        MarkerType.ATELIER_PAYSAN
    ),
    MarkerLieu(
        R.string.atelier_paysan,
        R.string.amakna_scara,
        1,
        23,
        MarkerType.ATELIER_PAYSAN
    ),
    MarkerLieu(
        R.string.atelier_paysan,
        R.string.bonta,
        -30,
        -42,
        MarkerType.ATELIER_PAYSAN
    )
)

val markerAtelierTailleurs = listOf(
    MarkerLieu(
        R.string.atelier_cordo,
        R.string.astrub_cite,
        1,
        -22,
        MarkerType.ATELIER_TAILLEUR
    ),
    MarkerLieu(
        R.string.atelier_cordo,
        R.string.amakna_village,
        2,
        2,
        MarkerType.ATELIER_TAILLEUR
    ),
    MarkerLieu(
        R.string.atelier_cordo,
        R.string.brakmar,
        -24,
        35,
        MarkerType.ATELIER_TAILLEUR
    ),
    MarkerLieu(
        R.string.atelier_tailleur,
        R.string.bonta,
        -31,
        -55,
        MarkerType.ATELIER_TAILLEUR
    )
)

val markerAtelierCordo = listOf(
    MarkerLieu(
        R.string.atelier_cordo,
        R.string.astrub_cite,
        0,
        -21,
        MarkerType.ATELIER_CORDO
    ),
    MarkerLieu(
        R.string.atelier_cordo,
        R.string.amakna_village,
        5,
        1,
        MarkerType.ATELIER_CORDO
    ),
    MarkerLieu(
        R.string.atelier_cordo,
        R.string.brakmar,
        -23,
        36,
        MarkerType.ATELIER_CORDO
    ),
    MarkerLieu(
        R.string.atelier_cordo,
        R.string.bonta,
        -30,
        -57,
        MarkerType.ATELIER_CORDO
    )
)

val markerAtelierSculpteur = listOf(
    MarkerLieu(
        R.string.atelier_scult,
        R.string.astrub_cite,
        2,
        -21,
        MarkerType.ATELIER_SCULPTEUR
    ),
    MarkerLieu(
        R.string.atelier_scult,
        R.string.amakna_foret,
        3,
        12,
        MarkerType.ATELIER_SCULPTEUR
    ),
    MarkerLieu(
        R.string.atelier_scult,
        R.string.amakna_bandit,
        14,
        20,
        MarkerType.ATELIER_SCULPTEUR
    ),
    MarkerLieu(
        R.string.atelier_scult,
        R.string.amakna_scara,
        2,
        30,
        MarkerType.ATELIER_SCULPTEUR
    ),
    MarkerLieu(
        R.string.atelier_scult,
        R.string.amakna_scara,
        5,
        29,
        MarkerType.ATELIER_SCULPTEUR
    ),
    MarkerLieu(
        R.string.atelier_scult,
        R.string.brakmar,
        -21,
        39,
        MarkerType.ATELIER_SCULPTEUR
    ),
    MarkerLieu(
        R.string.atelier_scult,
        R.string.bonta,
        -30,
        -59,
        MarkerType.ATELIER_SCULPTEUR
    )
)

val markerAtelierForgerons = listOf(
    MarkerLieu(
        R.string.atelier_forge,
        R.string.astrub_cite,
        6,
        -21,
        MarkerType.ATELIER_FORGERONS
    ),
    MarkerLieu(
        R.string.atelier_forge,
        R.string.amakna_village,
        -1,
        2,
        MarkerType.ATELIER_FORGERONS
    ),
    MarkerLieu(
        R.string.atelier_forge,
        R.string.brakmar,
        -21,
        34,
        MarkerType.ATELIER_FORGERONS
    ),
    MarkerLieu(
        R.string.atelier_forge,
        R.string.bonta,
        -26,
        -55,
        MarkerType.ATELIER_FORGERONS
    )
)

val markerAtelierAlchi = listOf(
    MarkerLieu(
        R.string.atelier_alchi,
        R.string.astrub_cite,
        5,
        -20,
        MarkerType.ATELIER_ALCHI
    ),
    MarkerLieu(
        R.string.atelier_alchi,
        R.string.amakna_bord_foret,
        1,
        16,
        MarkerType.ATELIER_ALCHI
    ),
    MarkerLieu(
        R.string.atelier_alchi,
        R.string.brakmar,
        -26,
        37,
        MarkerType.ATELIER_ALCHI
    ),
    MarkerLieu(
        R.string.atelier_alchi,
        R.string.bonta,
        -32,
        -55,
        MarkerType.ATELIER_ALCHI
    )
)

val markerAtelierMineurs = listOf(
    MarkerLieu(
        R.string.atelier_mineur,
        R.string.astrub_cite,
        7,
        -20,
        MarkerType.ATELIER_MINEUR
    ),
    MarkerLieu(
        R.string.atelier_mineur,
        R.string.amakna_montagne,
        -2,
        -3,
        MarkerType.ATELIER_MINEUR
    ),
    MarkerLieu(
        R.string.atelier_mineur,
        R.string.amakna_oree,
        -1,
        5,
        MarkerType.ATELIER_MINEUR
    ),
    MarkerLieu(
        R.string.atelier_mineur,
        R.string.amakna_scara,
        3,
        19,
        MarkerType.ATELIER_MINEUR
    ),
    MarkerLieu(
        R.string.atelier_mineur,
        R.string.brakmar,
        -20,
        33,
        MarkerType.ATELIER_MINEUR
    ),
    MarkerLieu(
        R.string.atelier_mineur,
        R.string.bonta,
        -28,
        -57,
        MarkerType.ATELIER_MINEUR
    )
)

val markerAtelierPecheur = listOf(
    MarkerLieu(
        R.string.atelier_poiss_pech,
        R.string.astrub_cite,
        2,
        -17,
        MarkerType.ATELIER_PECHEUR
    ),
    MarkerLieu(
        R.string.atelier_pech,
        R.string.amakna_kawaii,
        9,
        0,
        MarkerType.ATELIER_PECHEUR
    ),
    MarkerLieu(
        R.string.atelier_poiss_pech,
        R.string.sufokia,
        14,
        26,
        MarkerType.ATELIER_PECHEUR
    ),
    MarkerLieu(
        R.string.atelier_poiss_pech,
        R.string.brakmar,
        -24,
        40,
        MarkerType.ATELIER_PECHEUR
    ),
    MarkerLieu(
        R.string.atelier_poiss_pech,
        R.string.bonta,
        -35,
        -54,
        MarkerType.ATELIER_PECHEUR
    )
)


val markerAtelierBoulangers = listOf(
    MarkerLieu(
        R.string.atelier_boulanger,
        R.string.astrub_cite,
        2,
        -16,
        MarkerType.ATELIER_BOULANGER
    ),
    MarkerLieu(
        R.string.atelier_boulanger,
        R.string.amakna_village,
        3,
        0,
        MarkerType.ATELIER_BOULANGER
    ),
    MarkerLieu(
        R.string.atelier_boulanger,
        R.string.amakna_foret,
        4,
        13,
        MarkerType.ATELIER_BOULANGER
    ),
    MarkerLieu(
        R.string.atelier_boulanger,
        R.string.amakna_scara,
        -1,
        23,
        MarkerType.ATELIER_BOULANGER
    ),
    MarkerLieu(
        R.string.atelier_boulanger,
        R.string.amakna_scara,
        3,
        23,
        MarkerType.ATELIER_BOULANGER
    ),
    MarkerLieu(
        R.string.atelier_boulanger,
        R.string.brakmar,
        -22,
        32,
        MarkerType.ATELIER_BOULANGER
    ),
    MarkerLieu(
        R.string.atelier_boulanger,
        R.string.bonta,
        -27,
        -50,
        MarkerType.ATELIER_BOULANGER
    )
)

val markerAtelierBijou = listOf(
    MarkerLieu(
        R.string.atelier_bij,
        R.string.astrub_cite,
        5,
        -16,
        MarkerType.ATELIER_BIJOU
    ),
    MarkerLieu(
        R.string.atelier_bij,
        R.string.amakna_village,
        0,
        2,
        MarkerType.ATELIER_BIJOU
    ),
    MarkerLieu(
        R.string.atelier_bij,
        R.string.amakna_scara,
        2,
        29,
        MarkerType.ATELIER_BIJOU
    ),
    MarkerLieu(
        R.string.atelier_bij,
        R.string.brakmar,
        -27,
        39,
        MarkerType.ATELIER_BIJOU
    ),
    MarkerLieu(
        R.string.atelier_bij,
        R.string.bonta,
        -33,
        -59,
        MarkerType.ATELIER_BIJOU
    )
)

val markerAtelierBoucher = listOf(
    MarkerLieu(
        R.string.atelier_bouch_chass,
        R.string.astrub_cite,
        0,
        -15,
        MarkerType.ATELIER_BOUCHER
    ),
    MarkerLieu(
        R.string.atelier_chass,
        R.string.amakna_foret,
        1,
        13,
        MarkerType.ATELIER_BOUCHER
    ),
    MarkerLieu(
        R.string.atelier_bouch,
        R.string.brakmar,
        -29,
        32,
        MarkerType.ATELIER_BOUCHER
    ),
    MarkerLieu(
        R.string.atelier_bouch,
        R.string.bonta,
        -32,
        -50,
        MarkerType.ATELIER_BOUCHER
    )
)


val markerAtelierForgemage = listOf(
    MarkerLieu(
        R.string.atelier_fm,
        R.string.astrub_cite,
        -5,
        -12,
        MarkerType.ATELIER_FORGEMAGE
    ),
    MarkerLieu(
        R.string.atelier_fm,
        R.string.brakmar,
        -29,
        38,
        MarkerType.ATELIER_FORGEMAGE
    ),
    MarkerLieu(
        R.string.atelier_fm,
        R.string.bonta,
        -38,
        -55,
        MarkerType.ATELIER_FORGEMAGE
    )
)

val markerAtelierBrico = listOf(
    MarkerLieu(
        R.string.atelier_brico,
        R.string.brakmar,
        -28,
        35,
        MarkerType.ATELIER_BRICO
    ),
    MarkerLieu(
        R.string.atelier_brico,
        R.string.bonta,
        -27,
        -59,
        MarkerType.ATELIER_BRICO
    )
)

val markerAtelierFeeArti = listOf(
    MarkerLieu(
        R.string.atelier_fee,
        R.string.cania_massif,
        -16,
        -23,
        MarkerType.ATELIER_FEE_ARTI
    )
)